Repository FIS2425/workshift-svc, pull requests merged in 2024-11, with the labels that each got.

#17 Fix/13 implement publisher
  docker-compose.yml
  eslint.config.mjs
  openapi.md
  openapi.yaml
  package-lock.json
  package.json
  src/config/index.js
  src/config/rabbitmq.js
  src/controllers/workshiftController.js
  src/routes/workshiftRoutes.js
Labels: 😎 size/m, 📦 Dependencies, 🐳 Build

#27 chore(logger): updated format
  .env.example
  package-lock.json
  package.json
  src/config/logger.js
  src/controllers/workshiftController.js
  src/middleware/verifyAuth.js
  src/utils/kafkaTransport.js
Labels: 😎 size/m, ⚙️ Configuration, 📦 Dependencies

#28 refactor(controller): ensured req.headers is defined
  .github/renovate.json
  .github/workflows/api-doc.yml
  .github/workflows/docker-deploy.yml
  package-lock.json
  package.json
  src/controllers/workshiftController.js
  src/middleware/verifyAuth.js
  src/utils/kafkaTransport.js
Labels: 🚀 CI/CD, 😎 size/m, 📦 Dependencies

#34 feat(deploy): added kubernetes deploy
  .gitignore
  docker-compose.yml
  kubernetes/mongo-data-workshift-persistentvolumeclaim.yaml
  kubernetes/mongodb-deployment.yaml
  kubernetes/mongodb-service.yaml
  kubernetes/workshift-svc-deployment.yaml
  kubernetes/workshift-svc-service.yaml
  package.json
Labels: 😎 size/m, ⚙️ Configuration, 🐳 Dockerize, 📦 Dependencies, 🐳 Build
